### PR TITLE
Add React 17 as peer dependency

### PR DESCRIPTION
**Pull request by ayushmxn**
Addresses #214

### CODE REVIEW

**Comment by barnent1** [comment]
This Branch updates the repository to React v17. and React-Router-Dom to v6.0. All Packages, and Demo files have been updated to these changes.

**Comment by ayushmxn** [comment]
Hey @barnent1, looks like you're on the wrong branch. I believe this is your branch:

https://github.com/barnent1/react-email-editor/tree/UPGRADE_TO_REACT_V17

**Review by barnent1 — APPROVED** [review]

**Comment by barnent1** [comment]
> Hey @barnent1, looks like you're on the wrong branch. I believe this is your branch:
> 
> https://github.com/barnent1/react-email-editor/tree/UPGRADE_TO_REACT_V17

Yes this is the fixed branch which was a fork of the originial.

**Comment by hpaul** [comment]
👍

**Review by umairsiddique — APPROVED** [review]

**Pull request merged**
