### PR TITLE
Fix broken export in CJS and add missing methods

### PR DESCRIPTION
**Pull request by lucasbesen**

### CODE REVIEW

**Comment by andresmoschini** [comment]
❤️

**Comment by Sam-Apostel** [comment]
I just pushed my fork (https://github.com/Sam-Apostel/react-email-editor) which replaces the unmaintained TSDX with parcel.

I also implemented some extra types we were missing.

**Comment by novacoole** [comment]
Thanks @lucasbesen, this will resolve #327

**Comment by zhanghengxin** [comment]
I'm surprised that even the Master branch doesn't work.
Why not incorporate this now?

**Pull request merged**
