### PR TITLE
Fix window is not defined on server rendered apps

### PR DESCRIPTION
**Pull request by brunolemos**
Fix https://github.com/unlayer/react-email-editor/issues/364
Fix https://github.com/unlayer/react-email-editor/issues/376

### CODE REVIEW

**Comment by koralajoie** [comment]
Any idea when this might be merged?

**Comment by akichim21** [comment]
@adeelraza @lucasbesen @ivoIturrieta 
Could you merge this?

**Comment by mineraux** [comment]
Up on this fix. Is it possible to merge asap ?
@adeelraza @lucasbesen @ivoIturrieta

**Review by lucasbesen — APPROVED** [review]

**Comment by mineraux** [comment]
@adeelraza @ivoIturrieta Can we have some followup on this PR please ? This is quite blocking

**Review by kenri — APPROVED** [review]

**Pull request merged**
